spring.application.name=springSecurityTemplate

#spring.security.user.name = suman
#spring.security.user.password = 12345

server.servlet.session.cookie.same-site = strict

spring.datasource.url = jdbc:postgresql://localhost:5432/test_security
spring.datasource.username = postgres
spring.datasource.password = root

spring.jpa.show.sql = true
spring.jpa.hibernate.ddl-auto=update